// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TadbirKish.DataReception.Infrastructure.Persistence;

#nullable disable

namespace TadbirKish.DataReception.Infrastructure.Migrations
{
    [DbContext(typeof(DataReceptionContext))]
    [Migration("20251016083649_CreateDatabaseAndEnities")]
    partial class CreateDatabaseAndEnities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.Coverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Max")
                        .HasColumnType("bigint");

                    b.Property<long>("Min")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Coverages", "Data");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Coefficient = 0.0051999999999999998,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Max = 500000000L,
                            Min = 5000L,
                            Name = "جراحی"
                        },
                        new
                        {
                            Id = 2,
                            Coefficient = 0.0041999999999999997,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Max = 400000000L,
                            Min = 4000L,
                            Name = "دندانپزشکی"
                        },
                        new
                        {
                            Id = 3,
                            Coefficient = 0.0050000000000000001,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Max = 200000000L,
                            Min = 2000L,
                            Name = "بستری"
                        });
                });

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.RequestCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TotalNetPremium")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RequestCoverages", "Data");
                });

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.RequestCoverageDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CoverageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GrossPremium")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NetPremium")
                        .HasColumnType("float");

                    b.Property<int>("RequestCoverageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoverageId");

                    b.HasIndex("RequestCoverageId", "CoverageId")
                        .IsUnique();

                    b.ToTable("RequestCoverageDetails", "Data");
                });

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.RequestCoverageDetails", b =>
                {
                    b.HasOne("TadbirKish.DataReception.Domain.Entities.Coverage", "Coverage")
                        .WithMany("AllRequestCoverageDetails")
                        .HasForeignKey("CoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TadbirKish.DataReception.Domain.Entities.RequestCoverage", "RequestCoverage")
                        .WithMany("AllRequestCoverageDetails")
                        .HasForeignKey("RequestCoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coverage");

                    b.Navigation("RequestCoverage");
                });

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.Coverage", b =>
                {
                    b.Navigation("AllRequestCoverageDetails");
                });

            modelBuilder.Entity("TadbirKish.DataReception.Domain.Entities.RequestCoverage", b =>
                {
                    b.Navigation("AllRequestCoverageDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
